version: "3"

services:
  # The Cookie Factory backend in SpringBoot
  tcf-server:
    image: pcollet/tcf-spring-backend
    build:
        context: ./backend
        dockerfile: Dockerfile
        args:
            JAR_FILE: simpleTCFS-0.0.1-SNAPSHOT.jar
    container_name: server
    environment:
      - BANK_WITH_PORT=bank-system:9090
      - POSTGRES_HOST=postgres:5432
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${POSTGRES_HOST} -- java -jar /opt/app/app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT}'"
    depends_on:
      - bank-system
      - postgres

  # A simple java CLI
  tcf-cli:
    image: pcollet/tcf-spring-cli
    build:
        context: cli
        dockerfile: Dockerfile
        args:
            JAR_FILE: cli-0.0.1-SNAPSHOT.jar
    container_name: cli
    environment:
      - SERVER_WITH_PORT=tcf-server:8080
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${SERVER_WITH_PORT} -- java -jar /opt/app/app.jar'"
    depends_on:
      - tcf-server
    volumes:
      - ./cli/demo:/opt/app/demo
    stdin_open: true
    tty: true

  # An external bank service in NestJs
  bank-system:
    image: pcollet/tcf-bank-service
    build:
        context: bank
        dockerfile: Dockerfile
    container_name: bank
  
  postgres:
    image: postgres:15.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=tcf-db
