version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins_conf/
      dockerfile: jenkins.Dockerfile
    privileged: true
    user: root
    environment:
     - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    env_file:
        - ./env/.secrets.env
    networks:
      - cicd
    ports:
      - 8000:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
  agent:
    privileged: true
    build:
      context: ./jenkins_conf/
      dockerfile: jenkins-agent.Dockerfile
    user: root
    container_name: agent
    expose:
     - 22
    networks:
      - cicd
    env_file:
        - ./env/.secrets.env
    volumes:
     - '/var/run/docker.sock:/var/run/docker.sock'
  sonarqube:
    image: sonarqube:latest
    ports:
      - 8001:9000
    env_file:
        - ./env/.secrets.env
    networks:
      - cicd
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
networks:
  cicd:
volumes:
  jenkins_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: